### PR TITLE
Features/http proxy support

### PR DESCRIPTION
**Pull request by ramajd**
following from #301 and #350, this PR adds the support for HTTP proxy

### CODE REVIEW

**Comment by casperstorm** [comment]
@ramajd could you update the book as well with the new http variable?

**Comment by ramajd** [comment]
@casperstorm just updated the changelog and the book reference for proxy configuration

**Review by tarkah — APPROVED** [review]
I don't have a proxy to test with, but LGTM. Thanks for adding these :D

**Comment by ramajd** [comment]
@tarkah I tested both, since I have to use various proxies almost everyday to bypass the internet censorship.

**Pull request merged**
