### PR TITLE
Theme v2

### LINKED ISSUE #480: theme filenames don't match names
Many (all?) of the [community themes](https://halloy.squidowl.org/configuration/themes/community.html) with two word names have a dash in the filename (`the-name.toml`), but no dash in `theme = "the name"`.

This means they will not load, as the filename, `theme =` name, and `name =` in the config must *all three* match.

### PR DESCRIPTION
**Pull request by casperstorm**
Fixes #480, #416.

### CODE REVIEW

**Comment by casperstorm** [comment]
@andymandias try this first version of Light Ferra with this branch.
(Just create `ferra-light.toml` with below content)

```toml
[colors.general]
background = "#f4ece6"
horizontal_rule = "#e9d9ce"
unread_indicator = "#ffa07a"
border = "#ddd0c8"

[colors.text]
primary = "#685650"
secondary = "#a79891"
tertiary = "#a352c5"
success = "#74862d"
error = "#df525e"

[colors.buffer]
background = "#f1e5dd"
background_text_input = "#ecdcd0"
background_title_bar = "#eee0d6"
timestamp = "#ae9d95"
action = "#74862d"
topic = "#AB8A79"
highlight = "#f4d6c7"
code = "#a352c5"
nickname = "#c4486c"
url = "#6360d6"
selection = "#e6c6c3"
border_selected = "#c7b9b1"

[colors.buffer.server_messages]
default = "#c19317"

[colors.buttons.primary]
background = "#f4ece6"
background_hover = "#f1e5dd"
background_selected = "#eadad0"
background_selected_hover = "#e6d5c9"

[colors.buttons.secondary]
background = "#e9d5c8"
background_hover = "#dfc2ad"
background_selected = "#c9bca2"
background_selected_hover = "#bdb99b"
```

**Comment by andymandias** [comment]
> @andymandias try this first version of Light Ferra with this branch.

I really like how this is shaping up!

For some reason away users seem to render more transparent over here:
Screenshot from 2024-08-27 11-59-30

**Comment by casperstorm** [comment]
> > @andymandias try this first version of Light Ferra with this branch.
> 
> I really like how this is shaping up!
> 
> For some reason away users seem to render more transparent over here: Screenshot from 2024-08-27 11-59-30

You now are able to edit the "away_transparency" in the config file.

```toml
[buffer.channel.nicklist]
away_transparency = 0.6
```

**Comment by andymandias** [comment]
The new transparency settings work really well for me, thanks!

This is maybe an idea for later, but would it be feasible with the rich text additions to allow font style to be specified (as well as color)?  I think it could be nice to have server messages in italics, or something along those lines.

**Comment by casperstorm** [comment]
> The new transparency settings work really well for me, thanks!
> 
> This is maybe an idea for later, but would it be feasible with the rich text additions to allow font style to be specified (as well as color)? I think it could be nice to have server messages in italics, or something along those lines.

Thats a good idea. Perhaps we can tackle that next.

**Review by andymandias — APPROVED** [review]
Looks good to me!  The amount of color specificity added, and the clarity it brings to the color names, is really nice.  Really liking `ferra-light` as well, will be running it on my Ubuntu workstation.

Looks like some of the v1 themes didn't make the transition.  That's totally okay by me (that so many have been transitioned is truly a feat), but the changelog indicates otherwise.  Maybe we could encourage community submissions in the `#halloy` channel topic?

**Comment by casperstorm** [comment]
> Looks good to me! The amount of color specificity added, and the clarity it brings to the color names, is really nice. Really liking `ferra-light` as well, will be running it on my Ubuntu workstation.
> 
> Looks like some of the v1 themes didn't make the transition. That's totally okay by me (that so many have been transitioned is truly a feat), but the changelog indicates otherwise. Maybe we could encourage community submissions in the `#halloy` channel topic?

Good idea. We should do that once we release this version.

**Comment by dmd** [comment]
Now that nearly all the themes on https://halloy.squidowl.org/configuration/themes/community.html don't work, where do we get themes?

**Comment by casperstorm** [comment]
> Now that nearly all the themes on https://halloy.squidowl.org/configuration/themes/community.html don't work, where do we get themes?

From that page once we do a release 😃 we should however setup a documentation page for when running from main. L

**Pull request merged**
