### PR TITLE
Macaw themes

### PR DESCRIPTION
**Pull request by spoisseroux**
A light and dark theme that matches macOS light and dark themes

### CODE REVIEW

**Review by casperstorm — CHANGES_REQUESTED** [review]
Those look GREAT 👍🏻 We should place them in the [community part of the book](https://unstable.halloy.squidowl.org/configuration/themes/community).

1. Run main branch, and open up the theme editor.
2. Copy the url for each of your themes.
3. Update the following [file](https://github.com/squidowl/halloy/blob/main/book/src/configuration/themes/community.md).

**Comment by spoisseroux** [comment]
Thanks! How do I open up the theme editor?

**Comment by casperstorm** [comment]
> Thanks! How do I open up the theme editor?
> 
> 

Either from command bar or button from bottom of sidebar!

**Review by casperstorm — CHANGES_REQUESTED** [review]
You don't need any .toml file or screenshots inside the `assets/themes` otherwise it looks good!

**Comment by spoisseroux** [comment]
Got it; removed. Sorry about that

**Review by casperstorm — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
