### PR TITLE
Create dependabot file for automatic updates for the creates and removed Cargo.lock and added some issue templates

### PR DESCRIPTION
**Pull request by YouFoundAlpha**

### CODE REVIEW

**Comment by YouFoundAlpha** [comment]
Why I removed the Cargo.lock file is because of this https://github.com/rust-lang/cargo/issues/315

**Comment by casperstorm** [comment]
Let's have each PR solve a single problem. That way its easier for us to review, and have a discussion.
Here you have a few things going on:

* Adding PR templates 
* Adding Issue templates
* Adding dependabot.yml
* Removing Cargo.lock from version control

**Comment by YouFoundAlpha** [comment]
> Let's have each PR solve a single problem. That way its easier for us to review, and have a discussion. Here you have a few things going on:
> 
>     * Adding PR templates
> 
>     * Adding Issue templates
> 
>     * Adding dependabot.yml
> 
>     * Removing Cargo.lock from version control

Ok I'll make it

**Comment by tarkah** [comment]
> Why have removed the Cargo.lock file is because of this https://github.com/rust-lang/cargo/issues/315

This is only relevant for _library_ crates, not binary crates

**Pull request closed without merging**
