### PR TITLE
Add SHA256

### PR DESCRIPTION
**Pull request by YouFoundAlpha**

### CODE REVIEW

**Comment by YouFoundAlpha** [comment]
PR for #334

**Comment by YouFoundAlpha** [comment]
Keep in mind that the action only can get turned on manually and the files gets placed in the root of the repo

**Comment by casperstorm** [comment]
I was actually about to just add this functionally to our existing release action so the file is only added to the release and not in the repo. Will finish it up asap.

**Comment by YouFoundAlpha** [comment]
> I was actually about to just add this functionally to our existing release action so the file is only added to the release and not in the repo. Will finish it up asap. 

Sounds good

**Comment by casperstorm** [comment]
Added a manual action for now so I could target previous releases: https://github.com/squidowl/halloy/blob/main/.github/workflows/checksum.yml
I can add it to auto run on published releases later, in any case this is now solved :)

**Comment by YouFoundAlpha** [comment]
> Added a manual action for now so I could target previous releases: https://github.com/squidowl/halloy/blob/main/.github/workflows/checksum.yml
> I can add it to auto run on published releases later, in any case this is now solved :)

The usual names for the SHA256 hashes files are SHA256SUM or SHA256SUMS or checksums.txt

**Pull request closed without merging**
