### PR TITLE
Add Send Time to Broadcast Messages

### PR DESCRIPTION
**Pull request by andymandias**
This is an attempt to address the Halloy side of #226 by adding a `sent_time` to those broadcast messages.  Other broadcast messages I expect will not have such long times between send and receive, so I have not added `sent_time` to those messages, instead it defaults to `Utc::now()` at receive time (previous behavior).

### CODE REVIEW

**Comment by andymandias** [comment]
Shows the correct connect/disconnect times in the backlog for me.

**Review by casperstorm — COMMENTED** [review]
This makes sense to me, however is there a good way to test it?

**Comment by andymandias** [comment]
Okay, I can now consistently reproduce broadcast timestamps not matching when the event occurred with these steps (these may not be the minimum required yet, but they are consistently working for me):
1.  Sleep laptop with Halloy in another workspace.
2. Wake laptop, but do not return to the workspace with Halloy.
3.  On another computer enter the same channel and perform a broadcast action (e.g. use the webchat to log in to the channel and change nickname).
4.  Return to Halloy workspace.

**Review by tarkah — APPROVED** [review]
LGTM. Makes sense we would show server time on broadcast messages for better accuracy just like other messages, since they're based on a server message.

**Review by casperstorm — APPROVED** [review]

**Pull request merged**
